// Persistent snapshot of each connector's most recent successful fetch, as RAW
// connector results (origin/mirror/native representations). When a connector
// fails, the loader falls back to this file so a single broken source doesn't
// blank out the dashboard. The builder reconciles + merges these at build time;
// the snapshot itself stays raw.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { ConnectorResult, ProjectSource } from '../types/project';

export type ConnectorKey = Exclude<ProjectSource, 'manual'>;

export type ConnectorSnapshot = {
  /** ISO timestamp of the most recent successful fetch. */
  lastScrapedAt: string;
  results: ConnectorResult[];
};

export type SnapshotFile = {
  /** Snapshot schema version — bump on breaking changes. */
  version: 2;
  _generated: string;
  connectors: Partial<Record<ConnectorKey, ConnectorSnapshot>>;
};

// Resolved relative to cwd (project root under `npm run`), not the module URL —
// which moves into dist/ after Astro bundles.
const SNAPSHOT_PATH = resolve(process.cwd(), 'generated/snapshot.json');

const GENERATED_NOTE =
  'Auto-generated by the build. Raw per-connector results — do not hand-edit; regenerate via `npm run build`.';

function emptySnapshot(): SnapshotFile {
  return { version: 2, _generated: GENERATED_NOTE, connectors: {} };
}

export function readSnapshot(): SnapshotFile {
  if (!existsSync(SNAPSHOT_PATH)) return emptySnapshot();
  try {
    const parsed = JSON.parse(readFileSync(SNAPSHOT_PATH, 'utf8')) as SnapshotFile;
    if (parsed.version !== 2 || !parsed.connectors) return emptySnapshot();
    parsed._generated = GENERATED_NOTE;
    return parsed;
  } catch (err) {
    console.warn('[snapshot] read failed, starting empty:', err);
    return emptySnapshot();
  }
}

export function writeSnapshot(snapshot: SnapshotFile): void {
  mkdirSync(dirname(SNAPSHOT_PATH), { recursive: true });
  snapshot._generated = GENERATED_NOTE;
  writeFileSync(SNAPSHOT_PATH, JSON.stringify(snapshot, null, 2) + '\n', 'utf8');
}
